  CREATE TABLE "EBANK_UAT"."CUSTOMER" 
   (           "EBID" VARCHAR2(20 BYTE), 
                "FULL_NAME" VARCHAR2(500 BYTE), 
                "TITLE" VARCHAR2(5 BYTE), 
                "SEX" VARCHAR2(1 BYTE), 
                "DOB" DATE, 
                "MOB_NUMBER" VARCHAR2(20 BYTE), 
                "MOB_COUNTRY_CODE" VARCHAR2(20 BYTE), 
                "COLUMN1" VARCHAR2(20 BYTE), 
                "MOB_AREA_CODE" VARCHAR2(20 BYTE), 
                "OPT_IN" VARCHAR2(20 BYTE), 
                "PERM_EMAIL" VARCHAR2(50 BYTE), 
                "TEMP_EMAIL" VARCHAR2(50 BYTE), 
                "PERM_EMAIL_LAST_UPDATE_DATE" DATE, 
                "PERM_EMAIL_LAST_UPDATE_BY" VARCHAR2(50 BYTE), 
                "SKIP_EMAIL_UPDATE_PROCESS" VARCHAR2(1 BYTE), 
                "EBANK_TYPE" VARCHAR2(2 BYTE), 
                "STAFF_INDICATOR" VARCHAR2(1 BYTE), 
                "FIRST_REGISTRATION_DATE" DATE, 
                "RE_REGISTRATION_DATE" DATE, 
                "LAST_LOGIN_SUCCESSFUL_DATE" DATE, 
                "LOGIN_FAIL_COUNT" NUMBER, 
                "LAST_LOGIN_FAIL_DATE" DATE, 
                "BIOMETRIC_REMINDER_FLAG" VARCHAR2(1 BYTE), 
                "BIOMETRIC_REMINDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

